### ISSUE TITLE
Enabling the content_slug (v2.1.0) template breaks (header) layout (TYPO3v11.5.9)

### ISSUE THREAD

**Issue by alexsteffens** [sebkln/content_slug#11]
As soon as I activated the template, the layout of my headings was apparently changed. For example, they were no longer centred, the spacing was different and my custom css styles were undone.
I'm not sure if there were any other changes. But it was obvious with the header.

**Comment by sebkln** [comment]
EXT:content_slug provides extended Fluid templates for the headers of TYPO3 content elements. It seems that you already customized the same templates, which (of course) is quite common. In that case, you need to copy the template changes of this extension to your own custom templates.

The extension documentation shows you which parts are needed in which template: https://docs.typo3.org/p/sebkln/content-slug/2.1/en-us/Configuration/Templating/Index.html

You will also have to change the loading order of Fluid templates. The extension's rootPaths use the key `101`.
That means you have two choices:
- **Recommended:** set the key of **your** rootPaths to a higher value. That ensures that your TYPO3 website uses your templates first and can fall back to the templates to EXT:content_slug.
- Alternative: unset the extension rootPaths (as shown below). In that case, you **must** copy **all** template adjustments to your sitepackage! Otherwise, necessary markup/data will be missing e.g. in the Section Menus.

```
lib.contentElement {
    partialRootPaths.101 >
    templateRootPaths.101 >
}

**Comment by sebkln** [comment]
I'll close this now.

Feel free to re-open the issue if you have further questions.
