### ISSUE TITLE
Creation of dynamic property ReplaceFragment::$typoScriptSetup is deprecated

### ISSUE THREAD

**Issue by eliashaeussler** [sebkln/content_slug#17]
Hi @sebkln,

I currently get the following deprecation notice with version 3.0.1 of the extension and PHP 8.1.16 (TYPO3 11.5.24):

> PHP Runtime Deprecation Notice: Creation of dynamic property Sebkln\ContentSlug\Hooks\ReplaceFragment::$typoScriptSetup is deprecated in /var/www/html/app/web/typo3conf/ext/content_slug/Classes/Hooks/ReplaceFragment.php line 36

I wonder if this property is actually required since it's only assigned and never used.

Apart from that – thanks for this great extension 😊!

**Comment by sebkln** [comment]
Hey @eliashaeussler,

you're right of course! Thanks for letting me know. I now checked the other classes and the issue is also found in two other places:
- [FragmentIdentifierProcessor, Line 30](https://github.com/sebkln/content_slug/blob/master/Classes/DataProcessing/FragmentIdentifierProcessor.php#L30)
- [ModifyFragment, Line 34](https://github.com/sebkln/content_slug/blob/master/Classes/Listener/ModifyFragment.php#L34)

Would you be willing to remove these lines in your PR as well? Then I could merge the fixes in one go.

**Comment by eliashaeussler** [comment]
@sebkln Done :)
